
import React from 'react'
import ResetPassword from '../Components/ResetPassword'


export const metadata = {
  title: "YouTube | Reset Password",
  description: "Generated by create next app",
};


export default function Page() {
  
  return (
    <div>
      <ResetPassword/>
    </div>
  )
}
