
import WatchVideos from '@/app/Components/WatchVideos'
import React from 'react'


export const metadata = {
  title: "YouTube | Watch this video",
  description: "Generated by create next app",
};

export default function page() {
    
  return (
    <WatchVideos/>
  )
}
