import PlaylistVideos from '@/app/Components/PlaylistVideos'
import React from 'react'
export const metadata = {
  title: "YouTube | Playlist Containing Videos ",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <PlaylistVideos/>
  )
}
