import React from "react";
import RightSideBar from "./common/RightSideBar";


export const metadata = {
  title: "YouTube",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <>
    <RightSideBar/>
    </>
  );
}
