import UploadVideo from '@/app/Components/UploadVideo'
import React from 'react'


export const metadata = {
  title: "YouTube | Upload a Video",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
        <UploadVideo/>
    </>
  )
}
