import ChannelPage from '@/app/Components/ChannelPage';
import React from 'react'

export const metadata = {
  title: "VidShare | Channel Page",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
    <ChannelPage/>
    </>
  )
}
