import UserChannelPage from '@/app/Components/UserChannelPage';
import React from 'react'


export const metadata = {
  title: "VidShare | User Channel Page",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
    <UserChannelPage/>
    </>
  )
}
