import React from 'react'
import CreateYoutubeChannel from '../Components/CreateYoutubeChannel'

export const metadata = {
  title: "YouTube | Create Channel",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <CreateYoutubeChannel/>
  )
}
