import ViewDownloadedVideos from '@/app/Components/ViewDownloadedVideos'
import React from 'react'


export const metadata = {
  title: "VidShare | Downloaded Videos",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <ViewDownloadedVideos/>
  )
}
