import React from 'react'
import Help from '../Components/Help'

export const metadata = {
  title: "YouTube | Help From Community Posts",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
    <Help/>
    </>
  )
}
