import React from 'react'
import Settings from '../Components/Settings'


export const metadata = {
  title: "VidShare | Settings",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <Settings/>
  )
}
